package bankdb

import (
	"database/sql"
	"log"
	"os"
	"testing"

	_ "github.com/lib/pq"
)

const(
	dbDriver="postgres"
	dbSource="postgresql://root:password@localhost:5432/simple_bank?sslmode=disable"
)

var testQueries *Queries
var testDB *sql.DB

func TestMain(m *testing.M) {
	var err error
	testDB,err= sql.Open(dbDriver, dbSource)

	if err != nil {
		log.Fatal("cannot connect to db:",err)
	}

	//running the database using the New function in db.go generated by sqlc
	testQueries = New(testDB)

	os.Exit(m.Run())
}